// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ReadyResponse"
                        }
                    }
                }
            }
        },
        "/torrents": {
            "get": {
                "description": "Returns list of torrents in qBittorrent.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "List torrents in qBittorrent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TorrentListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "qbittorrent.TorrentInfo": {
            "type": "object",
            "properties": {
                "added_on": {
                    "type": "integer"
                },
                "amount_left": {
                    "type": "integer"
                },
                "auto_tmm": {
                    "type": "boolean"
                },
                "availability": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "completed": {
                    "type": "integer"
                },
                "completion_on": {
                    "type": "integer"
                },
                "content_path": {
                    "type": "string"
                },
                "dl_limit": {
                    "type": "integer"
                },
                "dlspeed": {
                    "type": "integer"
                },
                "download_path": {
                    "type": "string"
                },
                "downloaded": {
                    "type": "integer"
                },
                "downloaded_session": {
                    "type": "integer"
                },
                "eta": {
                    "type": "integer"
                },
                "f_l_piece_prio": {
                    "type": "boolean"
                },
                "force_start": {
                    "type": "boolean"
                },
                "has_metadata": {
                    "type": "boolean"
                },
                "hash": {
                    "type": "string"
                },
                "inactive_seeding_time_limit": {
                    "type": "integer"
                },
                "infohash_v1": {
                    "type": "string"
                },
                "infohash_v2": {
                    "type": "string"
                },
                "last_activity": {
                    "type": "integer"
                },
                "magnet_uri": {
                    "type": "string"
                },
                "max_inactive_seeding_time": {
                    "type": "integer"
                },
                "max_ratio": {
                    "type": "number"
                },
                "max_seeding_time": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "num_complete": {
                    "type": "integer"
                },
                "num_incomplete": {
                    "type": "integer"
                },
                "num_leechs": {
                    "type": "integer"
                },
                "num_seeds": {
                    "type": "integer"
                },
                "popularity": {
                    "type": "number"
                },
                "priority": {
                    "type": "integer"
                },
                "private": {
                    "type": "boolean"
                },
                "progress": {
                    "type": "number"
                },
                "ratio": {
                    "type": "number"
                },
                "ratio_limit": {
                    "type": "number"
                },
                "reannounce": {
                    "type": "integer"
                },
                "root_path": {
                    "type": "string"
                },
                "save_path": {
                    "type": "string"
                },
                "seeding_time": {
                    "type": "integer"
                },
                "seeding_time_limit": {
                    "type": "integer"
                },
                "seen_complete": {
                    "type": "integer"
                },
                "seq_dl": {
                    "type": "boolean"
                },
                "size": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "super_seeding": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "string"
                },
                "time_active": {
                    "type": "integer"
                },
                "total_size": {
                    "type": "integer"
                },
                "tracker": {
                    "type": "string"
                },
                "trackers_count": {
                    "type": "integer"
                },
                "up_limit": {
                    "type": "integer"
                },
                "uploaded": {
                    "type": "integer"
                },
                "uploaded_session": {
                    "type": "integer"
                },
                "upspeed": {
                    "type": "integer"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "response.HealthResponse": {
            "type": "object",
            "properties": {
                "connector_name": {
                    "type": "string"
                },
                "health_last_check": {
                    "type": "string"
                },
                "health_next_check": {
                    "type": "string"
                },
                "healthy": {
                    "type": "boolean"
                }
            }
        },
        "response.ReadyResponse": {
            "type": "object",
            "properties": {
                "ready": {
                    "type": "boolean"
                }
            }
        },
        "response.TorrentListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/qbittorrent.TorrentInfo"
                    }
                },
                "total_items": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Downloader Connector",
	Description:      "A connector that downloads data from various sources to the host.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
