// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.ReadyResponse"
                        }
                    }
                }
            }
        },
        "/notifications/downloader": {
            "post": {
                "description": "Accepts a downloader-originated notification payload and posts it to Slack.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Forward a connector-downloader event payload to Slack",
                "parameters": [
                    {
                        "description": "Downloader notification payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_request.DownloaderNotificationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.NotificationDeliveryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/grafana": {
            "post": {
                "description": "Accepts a Grafana Alerting webhook payload and posts it to Slack.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Forward a Grafana alert payload to Slack",
                "parameters": [
                    {
                        "description": "Grafana notification payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_request.GrafanaNotificationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.NotificationDeliveryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connector-notifications_internal_http_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "connector-notifications_internal_http_dto_request.DownloaderNotificationPayload": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/connector-notifications_internal_http_dto_request.NotificationAction"
                    }
                },
                "category": {
                    "type": "string"
                },
                "channel": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/connector-notifications_internal_http_dto_request.NotificationField"
                    }
                },
                "hash": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "severity": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "connector-notifications_internal_http_dto_request.GrafanaAlert": {
            "type": "object",
            "properties": {
                "annotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "dashboardURL": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "generatorURL": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "panelURL": {
                    "type": "string"
                },
                "silenceURL": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "valueString": {
                    "type": "string"
                }
            }
        },
        "connector-notifications_internal_http_dto_request.GrafanaNotificationPayload": {
            "type": "object",
            "properties": {
                "alerts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/connector-notifications_internal_http_dto_request.GrafanaAlert"
                    }
                },
                "channel": {
                    "type": "string"
                },
                "commonAnnotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "commonLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "externalURL": {
                    "type": "string"
                },
                "groupKey": {
                    "type": "string"
                },
                "groupLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "orgId": {
                    "type": "integer"
                },
                "receiver": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "truncatedAlerts": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "connector-notifications_internal_http_dto_request.NotificationAction": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "connector-notifications_internal_http_dto_request.NotificationField": {
            "type": "object",
            "properties": {
                "short": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "connector-notifications_internal_http_dto_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "upstream_response": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "connector-notifications_internal_http_dto_response.HealthResponse": {
            "type": "object",
            "properties": {
                "connector_name": {
                    "type": "string"
                },
                "health_last_check": {
                    "type": "string"
                },
                "health_next_check": {
                    "type": "string"
                },
                "healthy": {
                    "type": "boolean"
                }
            }
        },
        "connector-notifications_internal_http_dto_response.NotificationDeliveryResponse": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "connector-notifications_internal_http_dto_response.ReadyResponse": {
            "type": "object",
            "properties": {
                "ready": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Notifications Connector",
	Description:      "A connector that acts as a notifications controller that accepts payloads and sends notifications to different channels.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
