---
apiVersion: v1
kind: Service
metadata:
  name: teslamate-mcp
  namespace: mcp
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: teslamate-mcp
    port: 8888
    targetPort: 8888
  selector:
    app: teslamate-mcp
