global:
  createDefaultServiceAccount: false

defaultPodOptions:
  automountServiceAccountToken: true
  enableServiceLinks: true

controllers:
  mosquitto:
    replicas: 1
    revisionHistoryLimit: 1
    containers:
      mosquitto:
        image:
          repository: eclipse-mosquitto
          tag: "2"
        command: ["mosquitto", "-c", "mosquitto-no-auth.conf"]

service:
  mosquitto:
    controller: mosquitto
    ports:
      mosquitto:
        port: 1883

persistence:
  data-mosquitto:
    forceRename: data-mosquitto
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
    - path: /mosquitto/data
  config-mosquitto:
    forceRename: config-mosquitto
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
    - path: /mosquitto/config
