vikunja:
  image:
    tag: "2.1.0"

  ingress:
    main:
      enabled: false

  configMaps:
    api-config:
      enabled: true
      data:
        config.yml: |
          service:
            publicurl: "https://board.iaminyourpc.xyz"
          typesense:
            url: "http://vikunja-typesense:8108"
            apiKey: "typesense"

  env:
    HOME: /tmp
    VIKUNJA_DATABASE_TYPE: postgres
    VIKUNJA_DATABASE_HOST:
      valueFrom:
        secretKeyRef:
          name: data-postgresql-shared-vikunja
          key: pgbouncer-host
    VIKUNJA_DATABASE_PORT:
      valueFrom:
        secretKeyRef:
          name: data-postgresql-shared-vikunja
          key: pgbouncer-port
    VIKUNJA_DATABASE_USER:
      valueFrom:
        secretKeyRef:
          name: data-postgresql-shared-vikunja
          key: user
    VIKUNJA_DATABASE_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: data-postgresql-shared-vikunja
          key: password
    VIKUNJA_DATABASE_NAME:
      valueFrom:
        secretKeyRef:
          name: data-postgresql-shared-vikunja
          key: dbname

postgresql:
  enabled: false
