---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: home
  sources:
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    ref: values
  - repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: 0.x.x
    chart: victoriametrics
    helm:
      skipCrds: false
      valueFiles:
      - '$values/helm/monitoring/victoriametrics/values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
