// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ReadyResponse"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "post": {
                "description": "Send a custom notification to Slack with specified options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Send a custom notification to Slack",
                "parameters": [
                    {
                        "description": "Custom notification payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_request.NotificationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.NotificationStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/connector-downloader/torrent": {
            "post": {
                "description": "Accepts a payload from connector-downloader and posts it to Slack as a message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Forward a connector-downloader notification payload to send a Slack message",
                "parameters": [
                    {
                        "description": "Notification payload from connector-downloader",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_request.TorrentNotificationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.NotificationStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/grafana/alerts": {
            "post": {
                "description": "Accepts a Grafana Alerting webhook payload and posts it to Slack as a message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Forward a Grafana alert payload to send a Slack message",
                "parameters": [
                    {
                        "description": "Webhook payload from Grafana Alerting",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_request.GrafanaAlertNotificationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.NotificationStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connector-slack_internal_http_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "connector-slack_internal_http_dto_request.GrafanaAlertNotificationPayload": {
            "type": "object",
            "properties": {
                "alerts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/notifications.GrafanaAlertItem"
                    }
                },
                "commonAnnotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "commonLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "externalURL": {
                    "type": "string"
                },
                "groupKey": {
                    "type": "string"
                },
                "groupLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "orgId": {
                    "type": "integer"
                },
                "receiver": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "truncatedAlerts": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "connector-slack_internal_http_dto_request.NotificationOptionsPayload": {
            "type": "object",
            "properties": {
                "extra_text": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                },
                "user_icon": {
                    "type": "string"
                }
            }
        },
        "connector-slack_internal_http_dto_request.NotificationPayload": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                },
                "blocks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                },
                "channel_id": {
                    "type": "string"
                },
                "options": {
                    "$ref": "#/definitions/connector-slack_internal_http_dto_request.NotificationOptionsPayload"
                }
            }
        },
        "connector-slack_internal_http_dto_request.TorrentNotificationPayload": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "jellyfin_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qbittorrent_url": {
                    "type": "string"
                }
            }
        },
        "connector-slack_internal_http_dto_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "upstream_response": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "connector-slack_internal_http_dto_response.HealthResponse": {
            "type": "object",
            "properties": {
                "connector_name": {
                    "type": "string"
                },
                "health_last_check": {
                    "type": "string"
                },
                "health_next_check": {
                    "type": "string"
                },
                "healthy": {
                    "type": "boolean"
                }
            }
        },
        "connector-slack_internal_http_dto_response.NotificationStatus": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "connector-slack_internal_http_dto_response.ReadyResponse": {
            "type": "object",
            "properties": {
                "ready": {
                    "type": "boolean"
                }
            }
        },
        "notifications.GrafanaAlertItem": {
            "type": "object",
            "properties": {
                "annotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "dashboardURL": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "generatorURL": {
                    "type": "string"
                },
                "imageURL": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "panelURL": {
                    "type": "string"
                },
                "silenceURL": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Slack Connector",
	Description:      "A connector that sends notification messages in Slack channels.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
