---
apiVersion: v1
kind: Service
metadata:
  name: pihole-mcp
  namespace: mcp
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: pihole-mcp
    port: 8080
    targetPort: 8080
  selector:
    app: pihole-mcp
