---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sparkyfitness
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: apps
  sources:
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    ref: values
  - repoURL: oci://ghcr.io/codewithcj/charts/sparkyfitness
    targetRevision: 1.7.3
    chart: sparkyfitness
    helm:
      skipCrds: false
      valueFiles:
      - '$values/helm/apps/sparkyfitness/values.yaml'
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    path: manifests/apps/sparkyfitness
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sparkyfitness
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
