planeVersion: v1.2.2

ingress:
  enabled: false
  appHost: board.iaminyourpc.xyz
  ingressClass: nginx

worker:
  memoryLimit: 3Gi
  memoryRequest: 512Mi

# external_secrets:
#   app_env_existingSecret: app-env
