---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: home
  sources:
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    ref: values
  - repoURL: https://otwld.github.io/ollama-helm/
    targetRevision: 1.34.0
    chart: ollama
    helm:
      skipCrds: false
      valueFiles:
      - '$values/helm/apps/ollama/values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
