---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup-kv
  namespace: vault
spec:
  schedule: "0 3 * * *" # Every day at 03:00AM
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: script-vault-backup-kv
            configMap:
              name: script-vault-backup-kv
              defaultMode: 0755
          - name: auth-gcloud-storage
            secret:
              secretName: auth-gcloud-storage
              items:
                - key: key.json
                  path: key.json
          - name: backups
            hostPath:
              path: /media/martin/Data/Backups/Vault
              type: Directory
          containers:
          - name: vault-backup-kv
            image: skullfighter6/python:3.13-utils
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: script-vault-backup-kv
              mountPath: /scripts
            - name: auth-gcloud-storage
              mountPath: /var/run/gcp
              readOnly: true
            - name: backups
              mountPath: /backups
            command: ["/bin/sh", "-c", "set -e; python /scripts/backup.py --backup-vault --enable-local-backup"]
            env:
            - name: VAULT_KV_NAMES
              value: "home"
            - name: GCP_PROJECT
              value: "home-k8s"
            - name: GCP_BUCKET
              value: "vault-kv-backups"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LOCAL_BACKUP_DIR
              value: "/backups"
            - name: VAULT_SCHEME
              value: "http"
            - name: VAULT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: data-vault-sensitive
                  key: VAULT_ADDRESS
            - name: VAULT_ROOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: data-vault-sensitive
                  key: VAULT_ROOT_TOKEN
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/run/gcp/key.json"
