---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
  namespace: vault
spec:
  concurrencyPolicy: Forbid
  schedule: "*/3 * * * *" # Every 3 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 180
      backoffLimit: 1
      ttlSecondsAfterFinished: 600
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: script-vault-unseal
            configMap:
              name: script-vault-unseal
              defaultMode: 0755
          containers:
          - name: unseal
            image: hashicorp/vault:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: script-vault-unseal
              mountPath: /scripts
            command: ["/bin/sh", "/scripts/unseal.sh"]
            env:
            - name: VAULT_SCHEME
              value: "http"
            - name: VAULT_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: data-vault-sensitive
                  key: VAULT_ADDRESSES
            - name: VAULT_UNSEAL_KEYS
              valueFrom:
                secretKeyRef:
                  name: data-vault-sensitive
                  key: VAULT_UNSEAL_KEYS
