---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-slack
  namespace: fetch-api
  labels:
    app: connector-slack
    env: home
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: connector-slack
  template:
    metadata:
      labels:
        app: connector-slack
        env: home
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-fetch-api
      containers:
        - name: connector-slack
          image: ghcr.io/dragon699/home-k8s/fetch-api/connectors/slack:0.0.24
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          ports:
            - containerPort: 9069
          command: ["/app/slack"]
          envFrom:
            - secretRef:
                name: data-connector-slack
            - configMapRef:
                name: config-connector-slack
