---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-env
  namespace: plane
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/plane/app-env
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
