grafana:
  url: "http://grafana.monitoring.svc"
  apiKeySecret:
    name: auth-grafana-mcp
    key: GRAFANA_SA_TOKEN

extraArgs:
- -transport
- streamable-http
- -address
- 0.0.0.0:8000
- -allowed-hosts
- grafana-mcp.mcp.svc.cluster.local:8000,grafana-mcp.mcp.svc:8000,grafana-mcp.mcp:8000
