apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-openclaw-grafana
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: auth-openclaw-grafana
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: OPENCLAW_GATEWAY_TOKEN
    remoteRef:
      key: home/openclaw/data-openclaw
      property: OPENCLAW_GATEWAY_TOKEN
