---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-ui
  namespace: fetch-ui
  labels:
    app: fetch-ui
    env: home
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fetch-ui
  template:
    metadata:
      labels:
        app: fetch-ui
        env: home
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-fetch-ui
      containers:
        - name: fetch-ui
          image: ghcr.io/dragon699/home-k8s/fetch-ui:0.1.13
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-fetch-ui
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
