resources:
  jellyfin:
    requests:
      memory: 256Mi
      cpu: 0.2
    limits:
      memory: 6Gi
      cpu: 6

jellyfin:
  mediaVolumes:
    - name: windows-data
      readOnly: false
      existingClaim: jellyfin-media-windows-data
