resources:
  jellyfin:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 6Gi
      cpu: 6000m

probes:
  startupProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 180
  livenessProbe:
    timeoutSeconds: 5
  readinessProbe:
    timeoutSeconds: 5

jellyfin:
  mediaVolumes:
    - name: data
      readOnly: false
      existingClaim: jellyfin-media-data
