qbittorrent:
  replicaCount: 1

  strategy:
    type: Recreate

  extraEnv: []
  extraEnvFrom: []
  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  volumes:
  - name: qbittorrent-data
    persistentVolumeClaim:
      claimName: qbittorrent-data

  volumeMounts:
  - name: qbittorrent-data
    mountPath: /data

  config:
    persistence:
      enabled: true
      size: 5Gi

  ingress:
    enabled: false

  gluetun:
    enabled: false

  prometheusQbittorrentExporter:
    enabled: true

genericDevicePlugin:
  enabled: true
