---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: home
  sources:
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    ref: values
  - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.13.0
    chart: gha-runner-scale-set-controller
    helm:
      releaseName: gha-runner-scale-set-controller
  - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    targetRevision: 0.13.0
    chart: gha-runner-scale-set
    helm:
      releaseName: gha-runner-home
      valueFiles:
      - '$values/helm/infra/github-actions/values.yaml'
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    path: manifests/infra/github-actions
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: github
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
