---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: infra
  sources:
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    ref: values
  - repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1
    chart: longhorn
    helm:
      skipCrds: false
      valueFiles:
      - '$values/helm/infra/longhorn/values.yaml'
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    path: manifests/infra/longhorn
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
