---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: git@github.com:dragon699/charts.git
    targetRevision: main
    path: argocd-apps
    helm:
      valueFiles: ['$values/argocd/apps/*.yaml']
      valuesObject:
        template:
          finalizers: []
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: false
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jqPathExpressions:
    - .metadata.finalizers[]? | select(startswith("pre-delete-finalizer.argocd.argoproj.io") or startswith("post-delete-finalizer.argocd.argoproj.io"))
