{
 "title": "API Monitoring",
 "description": "Mobile API",
 "tags": [
  "prometheus",
  "prod",
  "asp",
  "mobile-api",
  "loki",
  "tempo",
  "app-monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\", process=\"w3wp\"}[$__rate_interval])) / sum(process_cpu_count{job=\"$job\", instance=\"$instance\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Errors Rate by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", error_type!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "  topk(\r\n    10, sum by (http_route, http_request_method, method_route) (\r\n      label_join(\r\n        max_over_time(\r\n          http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\"\r\n        )\r\n      )\r\n    )",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secured Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n  increase(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__range])\r\n)",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests by Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(increase(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__range]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_threads_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Queue Length",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_queue_length{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads Queue Length"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_thread_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Process Threads"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"\", error_type!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(http_client_open_connections{job=\"$job\", instance=\"$instance\"}[$__interval]) > 0",
       "legendFormat": "[{{ http_connection_state }}] [{{ server_address }}:{{ server_port }}] [{{ url_scheme }}{{ network_protocol_version }}]"
      }
     ]
    },
    {
     "title": "Routing Match Attempts",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (host_name,http_route)\r\n(rate(aspnetcore_routing_match_attempts_total{job=\"$job\", instance=\"$instance\", aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"true\" }[$__rate_interval])) > 0",
       "legendFormat": "{{host_name}}{{http_route}} fallback route"
      },
      {
       "expr": "sum by (host_name,http_route)\r\n(rate(aspnetcore_routing_match_attempts_total{job=\"$job\", instance=\"$instance\", aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"false\" }[$__rate_interval])) > 0",
       "legendFormat": "{{host_name}}{{http_route}} success"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success of Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (job, instance)\r\n(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code!~\"[4-5]..\"}[$__rate_interval]))\r\n/\r\nsum by (job, instance)\r\n(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))\r\n* 100",
       "legendFormat": "Requests Success"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(15, sum by (http_route) (rate(http_server_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) /\r\nsum by (http_route) (rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15, sum by (http_request_method,http_route,url_scheme,http_response_status_code)\r\n(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) > 0)",
       "legendFormat": "[{{ http_request_method }} → {{ http_response_status_code }}] [{{ http_route }}]"
      }
     ]
    },
    {
     "title": "Requests Rate (4XX/5XX Only)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(url_scheme, http_request_method, http_route, http_response_status_code, error_type)\r\n(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_response_status_code!~\"[1-3]..\"}[$__rate_interval])) > 0",
       "legendFormat": "[{{ http_request_method }} → {{ http_response_status_code }}] [{{ http_route }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Committed Memory Size"
      },
      {
       "expr": "max_over_time(\r\n  process_runtime_dotnet_gc_objects_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval]\r\n)",
       "legendFormat": "Objects Size"
      },
      {
       "expr": "irate(\r\n  process_runtime_dotnet_gc_allocations_size_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]\r\n)",
       "legendFormat": "Allocations Size"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "idelta(process_runtime_dotnet_gc_collections_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Generations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_heap_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Fragmentation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Duration of Queries",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(\r\n    15, histogram_quantile(\r\n        .95, sum(\r\n            rate(\r\n                traces_spanmetrics_latency_bucket{service_name=\"$job\", service_instance_id=\"$instance\", span_name=\"database\"}[$__rate_interval]\r\n            )\r\n        ) by (\r\n            le, service_name, service_instance_id, db_name, db_statement\r\n        )\r\n    ) > 0\r\n)",
       "legendFormat": "[{{ db_name }}] -> {{ db_statement }}"
      }
     ]
    },
    {
     "title": "Slow Queries (> 3 seconds)",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(\r\n    15, histogram_quantile(\r\n        .95, sum(\r\n            rate(\r\n                traces_spanmetrics_latency_bucket{service_name=\"$job\", service_instance_id=\"$instance\", span_name=\"database\"}[$__rate_interval]\r\n            )\r\n        ) by (\r\n            le, service_name, service_instance_id, db_name, db_statement\r\n        )\r\n    ) > 3\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"$job\", instance=\"$instance\", source=\"application-logs\", level=\"INFO\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({job=\"$job\", instance=\"$instance\", source=\"application-logs\", level=~\"WARN.*\"}[$__range])"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({job=\"$job\", instance=\"$instance\", source=\"application-logs\", level=\"ERROR\"}[$__range])"
      }
     ]
    },
    {
     "title": "Criticals",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({job=\"$job\", instance=\"$instance\", source=\"application-logs\", level=\"CRITICAL\"}[$__range])"
      }
     ]
    },
    {
     "title": "Incoming Logs by Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (level) (count_over_time({job=\"$job\", instance=\"$instance\", source=\"application-logs\"}[$__auto]))",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Total Errors / Criticals",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "topk(50, sum by (Message, Exception_Detail_Message, level) (\r\n    count_over_time(\r\n        {job=\"$job\", instance=\"$instance\"}\r\n        | json\r\n        | level =~ \"(ERROR|CRIT.*)\"\r\n        | label_format Exception_Detail_Message=`{{ regexReplaceAll \"(.*transaction-id: )(\\\\S+)(,.*Authz isn.t in progress.*)\" .Exception_Detail_Message \"$1<hidden>$3\" }}`\r\n        | label_format Exception_Detail_Message=`{{ regexReplaceAll \"(NOGROUP.*)(#)(\\\\d+)(.*)(:)(\\\\S+)(\\\\')(.*)\" .Exception_Detail_Message \"$1$2<hidden>$4$5<hidden>$7$8\" }}`\r\n        | label_format Exception_Detail_Message=`{{ regexReplaceAll \"(.*)(Имате още )(\\\\d+)( опита)(.*)\" .Exception_Detail_Message \"$1$2<hidden>$4$5\" }}`\r\n        [$__auto]\r\n    )\r\n))\r\n",
       "legendFormat": "{{ level }} [{{ Message }}] -> {{ Exception_Detail_Message }}"
      }
     ]
    },
    {
     "title": "Errors / Criticals",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{job=\"$job\", instance=\"$instance\", source=\"application-logs\"} |= `` | json | level=~\".*ERROR|CRITICAL.*\" | line_format \"[{{ .Message }}] -> {{ .exception_message }}\""
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "{job=\"$job\", instance=\"$instance\", source=\"application-logs\"} |= `` | json | level=~\"WARN.*\" | line_format \"[{{ .Message }}]\""
      }
     ]
    },
    {
     "title": "All Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "{job=\"$job\", instance=\"$instance\", source=\"application-logs\"} |= `` | json | line_format \"[{{ .Message }}]\""
      }
     ]
    }
   ]
  }
 ]
}