{
 "title": "Infra VM Monitoring",
 "description": "Mobile API",
 "tags": [
  "prometheus",
  "prod",
  "mobile-api",
  "windows",
  "windows_exporter",
  "infra-monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(windows_os_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_os_info{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=\"$job\",instance=\"$instance\",mode=\"idle\"}[$__rate_interval]))) * 100 "
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Incoming Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"$job\", instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Outgoing Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"$job\", instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_os_time{job=\"$job\", instance=\"$instance\"} - on () windows_process_start_time{job=\"$job\", instance=\"$instance\",process=\"Idle\",process_id=\"0\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{job=\"$job\",instance=\"$instance\"} / windows_cs_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{job=\"$job\", instance=\"$instance\", volume !~\"HarddiskVolume.+\"}",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) > 1)"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=\"$job\",instance=\"$instance\",mode=\"idle\"}[$__rate_interval]))) * 100 ",
     "legendFormat": "CPU Utilized"
    }
   ]
  },
  {
   "title": "CPU Usage by Mode",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{job=\"$job\", instance=\"$instance\",mode!=\"idle\"}[$__rate_interval])) by (mode)) / 16)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Load Per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (process) (rate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\", process !~\"Idle\"}[$__rate_interval]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (windows_os_physical_memory_free_bytes{job=\"$job\",instance=\"$instance\"} / windows_cs_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}) * 100",
       "legendFormat": "Memory Used"
      }
     ]
    },
    {
     "title": "Memory Usage by Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_cs_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "RAM Total",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_physical_memory_free_bytes{job=\"$job\",instance=\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "RAM Free",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_virtual_memory_bytes{job=\"$job\",instance=\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "RAM Total Virtual",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "RAM Free Virtual"
      }
     ]
    },
    {
     "title": "Memory Commited Per Process",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (process) (windows_process_private_bytes{job=\"$job\", instance=\"$instance\", process!=\"\"})",
       "legendFormat": "{{ process }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (windows_logical_disk_free_bytes{job=\"$job\", instance=\"$instance\"} / windows_logical_disk_size_bytes{job=\"$job\", instance=\"$instance\"})*100",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk R/W C:\\",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{job=\"$job\", instance=\"$instance\", volume=\"C:\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "- irate(windows_logical_disk_read_bytes_total{job=\"$job\", instance=\"$instance\", volume=\"C:\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Disk R/W Other Volumes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_read_bytes_total{job=\"$job\",instance=\"$instance\", volume!=\"C:\"}[$__rate_interval])\r\n",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{job=\"$job\",instance=\"$instance\", volume!=\"C:\"}[$__rate_interval])\r\n",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_reads_total{job=\"$job\",instance=\"$instance\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_writes_total{job=\"$job\",instance=\"$instance\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Disk I/O Split Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(windows_logical_disk_split_ios_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Disk I/O Per Process",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (process) (rate(windows_process_io_bytes_total{job=\"$job\", instance=\"$instance\", mode=\"read\"}[$__rate_interval])) > 0",
       "legendFormat": "Read {{ process }}"
      },
      {
       "expr": "- avg by (process) (rate(windows_process_io_bytes_total{job=\"$job\", instance=\"$instance\", mode=\"write\"}[$__rate_interval])) < 0",
       "legendFormat": "Write {{ process }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(windows_net_bytes_sent_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) > 0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Upload",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "- rate(windows_net_bytes_received_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) < 0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Download",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network Incoming/Outgoing Per Hour",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(windows_net_bytes_received_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Download"
      },
      {
       "expr": "sum(increase(windows_net_bytes_sent_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "Network Discarded/Error Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_outbound_discarded_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) + irate(windows_net_packets_outbound_errors_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Upload",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_outbound_discarded_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) + irate(windows_net_packets_outbound_errors_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Download",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_os_processes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Number of processes"
      }
     ]
    },
    {
     "title": "System Threads",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Threads",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "System Threads Per Process",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "avg by (process) (windows_process_threads{job=\"$job\", instance=\"$instance\"})",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ process }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Exception Dispatches",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_system_exception_dispatches_total{job=\"$job\",instance=\"$instance\"}[$__rate_interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Exceptions",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}