---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-radar
  namespace: radar
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-radar
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/radar/auth-radar
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-radar-argocd
  namespace: radar
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-radar-argocd
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/radar/auth-radar-argocd
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
