{
 "title": "Longhorn",
 "tags": [
  "home",
  "victoriametrics",
  "kubernetes",
  "longhorn",
  "self-monitoring",
  "storage-provisioner",
  "storage",
  "volumes",
  "persistent-volumes",
  "persistence"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(longhorn_volume_state,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(longhorn_volume_state{job=\"$job\"},cluster)"
    }
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": {
     "query": "label_values(longhorn_volume_state{job=\"$job\", cluster=\"$cluster\"},volume)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(longhorn_node_count_total{job=\"$job\", cluster=\"$cluster\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Schedulable Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(longhorn_node_status{condition=\"schedulable\", job=\"$job\", cluster=\"$cluster\"}==1) OR on() vector(0)) - (count(longhorn_node_status{condition=\"allowScheduling\", job=\"$job\", cluster=\"$cluster\"}==0) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Failed Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg(longhorn_node_count_total{job=\"$job\", cluster=\"$cluster\"}) OR on() vector(0)) - (count(longhorn_node_status{condition=\"ready\", job=\"$job\", cluster=\"$cluster\"}==1) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Disabled Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_node_status{condition=\"allowScheduling\", job=\"$job\", cluster=\"$cluster\"}==0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_capacity_bytes{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}==1) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Attached Volumes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Faulty Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Degraded Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Detached Volumes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}==3) OR on() vector(0)"
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Volumes Storage Utilization",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (volume) (longhorn_volume_capacity_bytes{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "avg by (volume, name) (label_replace(kubelet_volume_stats_used_bytes, \"name\", \"$1\", \"persistentvolumeclaim\", \"(.*)\") * on(name) group_left(volume) (label_replace(kube_persistentvolume_claim_ref{persistentvolume=~\"$volume\"}, \"volume\", \"$1\", \"persistentvolume\", \"(.*)\")))",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 / avg by (volume) (longhorn_volume_capacity_bytes{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"})\r\n*\r\navg by (volume) (label_replace(kubelet_volume_stats_used_bytes, \"name\", \"$1\", \"persistentvolumeclaim\", \"(.*)\") * on(name) group_left(volume, persistentvolume) (label_replace(kube_persistentvolume_claim_ref{persistentvolume=~\"$volume\"}, \"volume\", \"$1\", \"persistentvolume\", \"(.*)\")))",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Volumes Actual Size Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (avg by (pvc) (longhorn_volume_actual_size_bytes{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"}))/ (avg by (pvc) (longhorn_volume_capacity_bytes{volume=~\"$volume\", job=\"$job\", cluster=\"$cluster\"})) ) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes Per Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (instance) (longhorn_volume_state{job=\"$job\", cluster=\"$cluster\"}==2)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Storage",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_node_storage_capacity_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      },
      {}
     ]
    },
    {
     "title": "Storage Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_node_storage_usage_bytes{job=\"$job\", cluster=\"$cluster\"}/longhorn_node_storage_capacity_bytes{job=\"$job\", cluster=\"$cluster\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_node_cpu_usage_millicpu{job=\"$job\", cluster=\"$cluster\"} / longhorn_node_cpu_capacity_millicpu{job=\"$job\", cluster=\"$cluster\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( longhorn_node_memory_usage_bytes{job=\"$job\", cluster=\"$cluster\"} / longhorn_node_memory_capacity_bytes{job=\"$job\", cluster=\"$cluster\"} ) * 100"
      }
     ]
    },
    {
     "title": "CPU Usage of Instance Manager",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "milicpu" } },
     "targets": [
      {
       "expr": "longhorn_instance_manager_cpu_usage_millicpu{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage of Instance Manager",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_instance_manager_memory_usage_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Usage of Longhorn Manager",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "milicpu" } },
     "targets": [
      {
       "expr": "longhorn_manager_cpu_usage_millicpu{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage of Longhorn Manager",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_manager_memory_usage_bytes{job=\"$job\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Instance Manager CPU Used from Request",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_instance_manager_cpu_usage_millicpu{job=\"$job\", cluster=\"$cluster\"}/longhorn_instance_manager_cpu_requests_millicpu{job=\"$job\", cluster=\"$cluster\"})*100",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}