controller:
  replicaCount: 1
  hostNetwork: true

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  allowSnippetAnnotations: true

  service:
    externalTrafficPolicy: Local

  config:
    use-forwarded-headers: "true"
    enable-real-ip: "true"
