---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-mirrors
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: home
  sources:
  - repoURL: https://charts.kts.studio
    targetRevision: 0.1.9
    chart: mirrors
  - repoURL: git@github.com:dragon699/home-k8s.git
    targetRevision: main
    path: manifests/secret-mirrors
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
