app-template:
  configMode: overwrite

  controllers:
    main:
      containers:
        main:
          envFrom:
            - secretRef:
                name: data-openclaw

  configMaps:
    config:
      enabled: true
