app-template:
  configMode: overwrite

  controllers:
    main:
      containers:
        main:
          envFrom:
            - secretRef:
                name: data-openclaw

  configMaps:
    config:
      enabled: false

  persistence:
    config:
      enabled: true
      type: custom
      volumeSpec:
        configMap:
          name: config-openclaw
      advancedMounts:
        main:
          init-config:
            - path: /config
              readOnly: true
    bash-aliases:
      enabled: true
      type: custom
      volumeSpec:
        configMap:
          name: config-openclaw
      advancedMounts:
        main:
          main:
            - path: /home/node/.bash_aliases
              subPath: bash_aliases
              readOnly: true
