app-template:
  controllers:
    main:
      containers:
        main:
          envFrom:
            - secretRef:
                name: data-openclaw

  configMaps:
    config:
      data:
        openclaw.json: |
          {
            // Gateway configuration
            "gateway": {
              "port": 18789,
              "mode": "local",
              "trustedProxies": [],
              "controlUi": {
                "dangerouslyAllowHostHeaderOriginFallback": true
              }
            }
          }
