---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-immich-mcp
  namespace: mcp
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-immich-mcp
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/mcp/auth-immich-mcp
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
